/*
 * PORT_private.h
 *
 *  Created on: Sep 11, 2022
 *      Author: ME
 */

#ifndef MCAL_PORT_PORT_PRIVATE_H_
#define MCAL_PORT_PORT_PRIVATE_H_

#define CONC(b7,b6,b5,b4,b3,b2,b1,b0)				CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)
#define CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)		0b##b7##b6##b5##b4##b3##b2##b1##b0

#define PORTA_DIR				CONC(PORTA_PIN7_DIR,PORTA_PIN6_DIR,PORTA_PIN5_DIR,PORTA_PIN4_DIR,PORTA_PIN3_DIR,PORTA_PIN2_DIR,PORTA_PIN1_DIR,PORTA_PIN0_DIR)
#define PORTB_DIR				CONC(PORTB_PIN7_DIR,PORTB_PIN6_DIR,PORTB_PIN5_DIR,PORTB_PIN4_DIR,PORTB_PIN3_DIR,PORTB_PIN2_DIR,PORTB_PIN1_DIR,PORTB_PIN0_DIR)
#define PORTC_DIR	            CONC(PORTC_PIN7_DIR,PORTC_PIN6_DIR,PORTC_PIN5_DIR,PORTC_PIN4_DIR,PORTC_PIN3_DIR,PORTC_PIN2_DIR,PORTC_PIN1_DIR,PORTC_PIN0_DIR)
#define PORTD_DIR	            CONC(PORTD_PIN7_DIR,PORTD_PIN6_DIR,PORTD_PIN5_DIR,PORTD_PIN4_DIR,PORTD_PIN3_DIR,PORTD_PIN2_DIR,PORTD_PIN1_DIR,PORTD_PIN0_DIR)

#define PORTA_INITIAL			CONC(PORTA_PIN7_INITIAL,PORTA_PIN6_INITIAL,PORTA_PIN5_INITIAL,PORTA_PIN4_INITIAL,PORTA_PIN3_INITIAL,PORTA_PIN2_INITIAL,PORTA_PIN1_INITIAL,PORTA_PIN0_INITIAL)
#define PORTB_INITIAL			CONC(PORTB_PIN7_INITIAL,PORTB_PIN6_INITIAL,PORTB_PIN5_INITIAL,PORTB_PIN4_INITIAL,PORTB_PIN3_INITIAL,PORTB_PIN2_INITIAL,PORTB_PIN1_INITIAL,PORTB_PIN0_INITIAL)
#define PORTC_INITIAL           CONC(PORTC_PIN7_INITIAL,PORTC_PIN6_INITIAL,PORTC_PIN5_INITIAL,PORTC_PIN4_INITIAL,PORTC_PIN3_INITIAL,PORTC_PIN2_INITIAL,PORTC_PIN1_INITIAL,PORTC_PIN0_INITIAL)
#define PORTD_INITIAL           CONC(PORTD_PIN7_INITIAL,PORTD_PIN6_INITIAL,PORTD_PIN5_INITIAL,PORTD_PIN4_INITIAL,PORTD_PIN3_INITIAL,PORTD_PIN2_INITIAL,PORTD_PIN1_INITIAL,PORTD_PIN0_INITIAL)

#endif /* MCAL_PORT_PORT_PRIVATE_H_ */
